### ISSUE TITLE
Bluetooth Hack

### ISSUE THREAD

**Issue by hornet72** [francozappa/bluffs#2]
Fremde Bluetooth Geräte hacken

**Comment by EsmeraldaYS** [comment]
how to use??

**Comment by 1-tong** [comment]
How is it used? What is the hardware carrier? Could you please answer this? Thank you!

**Comment by Meadril** [comment]
If you were really interested, you would have read this outstanding work. It describes everything.

[https://francozappa.github.io/post/2023/bluffs-ccs23/](https://francozappa.github.io/post/2023/bluffs-ccs23/) -> Read through the paper and then you'll know
